# Generated by Django 3.2.6 on 2021-08-30 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('상의', '상의')], default='상의', max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizeName', models.CharField(max_length=255)),
                ('size1', models.CharField(max_length=255)),
                ('size2', models.CharField(blank=True, max_length=255, null=True)),
                ('size3', models.CharField(blank=True, max_length=255, null=True)),
                ('size4', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size', to='MySizeApp.clothes')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='MySizeApp.clothes')),
            ],
        ),
    ]
