# Generated by Django 3.2.6 on 2021-08-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySizeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
